### ISSUE TITLE
0.17.0 can't be built

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-verification-server#1194]
### TL;DR
0.17.0 is missing oe.StartExporter argument

I'm getting:
```
not enough arguments in call to oe.StartExporter
	have ()
	want (context.Context)
```
it is fixed here:
https://github.com/google/exposure-notifications-verification-server/commit/f2f83107943c7077bf9866c4230511498ca054fd

**Expected behavior**
0.17.0 can be built

**Possible solution**
Can somebody do 0.17.1 with this commit cherry-picked?

thanks.

**Comment by mikehelmick** [comment]
/assign @whaught 

I think this has just been fixed - if so, can you cut a .1

**Comment by whaught** [comment]
This was corrected shortly after the branch was made. Should work in 0.17.0

**Comment by whaught** [comment]
https://github.com/google/exposure-notifications-verification-server/commit/f2f83107943c7077bf9866c4230511498ca054fd

**Comment by whaught** [comment]
Ensured the 0.17.0 branch tag includes commit https://github.com/google/exposure-notifications-verification-server/commit/f2f83107943c7077bf9866c4230511498ca054fd as intended.

/close
